### ISSUE TITLE
Suggestion for default text editor

### ISSUE THREAD

**Issue by danielabar** [ladieslearningcode/llc-html-css-multi-page-site#8]
I volunteered to mentor for the upcoming HTML/CSS workshop in June, and was just going over the slides to be prepared. 

For suggested text editor, it says Sublime as the default, or for Mac users suggests Atom or Windows users Notepad++.

Atom works pretty well on Windows now, so it could be the default choice for everyone. Some advantages over Sublime are:
* free (with no purchase popup every so many saves)
* easier to use plugin manager
* similar keyboard shortcuts to Sublime, so those coming from Sublime will feel instantly comfortable in Atom

If you think it's a good idea to switch to Atom, I could submit a PR for changing that slide (haven't used RevealJS before but seems fairly straightforward).

**Comment by christinatruong** [comment]
@danielabar Thanks for the suggestion! I agree that Atom, at this point, is a better choice as a default and have been thinking about updating it. There are some instructions that go out in confirmation emails to download Sublime before the workshop, so I'll need to make sure the slide updates correspond with that. Why don't you go ahead and make that PR but I may not merge the request until the related stuff is coordinated.  

Since it's just a content update, it should be pretty simple but you can view specific documentation for using the LLC slide deck here: http://ladieslearningcode.github.io/llc-slidedeck-template/slides.html#slide1

Thanks!

**Comment by danielabar** [comment]
I made the change in my fork, however, when running `git diff` shows a whole bunch of whitespace changes. I suspect due to different editor config settings. What is the convention used on this project? For example tabs vs spaces, 2 vs 4, line endings etc?

If you like, I can introduce an [.editorconfig file](http://editorconfig.org/#overview) along with the PR, to keep all the whitespace and formatting consistent among all contributors

**Comment by christinatruong** [comment]
It's mostly 2 spaces but admittedly not consistent :(  However, the line endings are most likely needed since Markdown requires 2 space to create a line break.  An .editorconfig file would be amazing.  Thanks!!

**Comment by christinatruong** [comment]
Updated to Atom! Thanks :)
